/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HaplotypeCaller */

#ifndef _Included_org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller
#define _Included_org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HaplotypeCaller
 * Method:    nativePrint
 * Signature: (JJJJJJJIIIII)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller_nativePrint
  (JNIEnv *, jobject, jlong*, jlong*, jlong*, jlong*, jlong*, jlong*, jlong*, jint, jint, jint, jint, jint);

/*
 * Class:     HaplotypeCaller
 * Method:    freeAccel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_tools_walkers_haplotypecaller_HaplotypeCaller_freeAccel
  (JNIEnv *, jobject, jlong*);

#ifdef __cplusplus
}
#endif
#endif
